apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.destination.repo }}
  description: ${{ values.name }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - typescript

spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
