version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000

  datadog-agent:
    image: 'gcr.io/datadoghq/agent:latest'
    hostname: 'datadog-agent'
    restart: 'on-failure'
    environment:
      - 'DD_API_KEY=5bee66aca7b120143bdd67138409d39b'
      - 'DD_ENV=local'
      - 'DD_APM_ENABLED=true'
      - 'DD_SITE=datadoghq.com'
      - 'DD_APM_NON_LOCAL_TRAFFIC=true'
      - 'DD_PROCESS_AGENT_ENABLED=true'
      - 'DD_LOGS_ENABLED=true'
      - 'DD_PROCFS_PATH=/proc'
      - 'DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true'
      - 'DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true'
      - 'DD_CONTAINER_EXCLUDE=name:datadog-agent'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/proc/:/host/proc/:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    ports:
      - 8126:8126
