version: '3'

env_file:
  - ./config/development.env

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
