services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - LOG_PRETTY=true
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
