version: '3'

services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - api

  k6:
    image: loadimpact/k6
    volumes:
      - ./test/load:/load
    networks:
      - api
    depends_on:
      - server

networks:
  api: {}
