name: load

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: start server
        run: docker compose -f load-test-compose.yaml up -d server

      - name: wait for server
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:3000
          timeout: 30000

      - name: load test
        run: npm run test:load
